### ISSUE TITLE
The Plan

### ISSUE THREAD

**Issue by mmmries** [ruby-protobuf/protobuf-core#1]
![the plan](http://embraceurdestiny.com/wp-content/uploads/2014/12/Got-a-Plan.jpg)

Before we go down the road of changing what code gets generated by `protobuf-core` I thought it would probably be valuable to create `protobuf-core`, `protobuf-rpc` and `protobuf-zmq` in a form that matches the current `protobuf` gem. We can keep the version numbers in the `3.X` series and just get the code organized into the new shape we want. Then we can start to experiment with changing what code is generated etc.

Does this sound like a good plan? If so I will make a `3.X` milestone and create some issues to track what I'm working on and I'll defer experimenting with the generator until we get things to a workable state.

/cc @localshred @liveh2o

**Comment by localshred** [comment]
Yes I agree, we need to have a version of protobuf-core, et al, that mirrors the current API in a stable release. Then we can break all the things.

**Comment by localshred** [comment]
Nice giant image btw... :wink:

**Comment by mmmries** [comment]
@nelsonwittwer and @vintagepenguin have infected me with the need to put images in all github discussions. I'm a victim here :ambulance: :mask: :sob:

**Comment by vintagepenguin** [comment]
hahaha @mmmries! @nelsonwittwer it continues....

**Comment by mmmries** [comment]
I have all unit tests (applicable to core functionality) copied from the `protobuf` gem and they are all passing now in this project. There is still some work to do before we are ready to release a version of this gem, but we're well on our way so I'm closing this issue.
